#! /bin/bash

cat $1 | grep td|
    tr -d '[:blank:]'| tr -d '\r'|tr '[:upper:]' '[:lower:]'|
    grep '<td>.*</td>' | sed 's/<[^>]*>//g' | sed 's/,/\n/g'|
    egrep '^[^bcdfgjqrstwxyz]+$' |  sed "s/\`/\'/g" | sort -u


# tr -d '<small>.*</small>'
